### ISSUE TITLE
metadata attribute ought to be in JSON (was YAML) format

### ISSUE THREAD

**Issue by dankelley** [dankelley/ocencdf#13]
The advantage of this is that I would be very surprised if e.g. python, julia, or any other analysis language could not translate yaml into something analogous to the `list` object in R.

The following shows how this can work.  Note that `as.yaml()` doesn't handle `expression` objects (which I discovered by trial and error).

I'll do this tomorrow.

```R
library(oce)
library(yaml)
data(ctd)
metadata <- ctd@metadata
# as.yaml does not handle 'expression' objects, as in units
for (i in seq_along(metadata$units))
    metadata$units[[i]]$unit <- as.character(metadata$units[[i]]$unit)
yaml <- as.yaml(metadata)
cat(yaml)
```

Output:
```
units:
  scan:
    unit: []
    scale: ''
  timeS:
    unit: s
    scale: ''
  pressure:
    unit: dbar
    scale: ''
  depth:
    unit: m
    scale: ''
  temperature:
    unit: degree * C
    scale: IPTS-68
  salinity:
    unit: []
    scale: PSS-78
  flag:
    unit: []
    scale: ''
flags: []
pressureType: sea
deploymentType: unknown
waterDepth: .na
dataNamesOriginal:
  scan: scan
  timeS: timeS
  pressure: pr
  depth: depS
  temperature: t068
  salinity: sal00
  flag: flag
model: '25'
header:
- '* Sea-Bird SBE 25 Data File:'
- '* FileName = C:\SEASOFT3\BASIN\BED0302.HEX'
- '* Software Version 4.230a'
- '* Temperature SN = 1140'
- '* Conductivity SN = 832'
- '* System UpLoad Time = Oct 15 2003 11:38:38'
- '* Command Line = seasave '
- '** Ship:      Divcom3'
- '** Cruise:    Halifax Harbour'
- '** Station:   Stn 2'
- '** Latitude:  N44 41.056'
- '** Longitude: w63 38.633'
- '* Real-Time Sample Interval = 1.000 seconds'
- '# nquan = 7'
- '# nvalues = 773                     '
- '# units = metric'
- '# name 0 = scan: scan number'
- '# name 1 = timeS: time [s]'
- '# name 2 = pr: pressure [db]'
- '# name 3 = depS: depth, salt water [m]'
- '# name 4 = t068: temperature, IPTS-68 [deg C]'
- '# name 5 = sal00: salinity, PSS-78 [PSU]'
- '# name 6 = flag:  0.000e+00'
- '# span 0 = 1, 773                       '
- '# span 1 = 0.000, 772.000               '
- '# span 2 = -0.378, 163.899              '
- '# span 3 = -0.375, 162.504              '
- '# span 4 = 2.3237, 99.0000              '
- '# span 5 = 0.3276, 99.0000              '
- '# span 6 = 0.000e+00, 0.000e+00         '
- '# interval = seconds: 1                           '
- '# start_time = Oct 15 1903 11:38:38'
- '# bad_flag = -9.990e-29'
- '# sensor 0 = Frequency 0  temperature, 1140, 13 Mar 03'
- '# sensor 1 = Frequency 1  conductivity, 832, 13 Mar 03, cpcor = -9.5700e-08'
- '# sensor 2 = Pressure Voltage, 145033, 17 Mar 03, cpcor = -9.5700e-08'
- '# sensor 3 = Stored Volt  0  transmissometer'
- '# datcnv_date = Oct 15 2003 13:46:47, 4.230a'
- '# datcnv_in = BED0302.HEX BED0301.CON'
- '# datcnv_skipover = 0'
- '# file_type = ascii'
- '*END*'
type: SBE
hexfilename: c:\seasoft3\basin\bed0302.hex
serialNumber: ''
serialNumberTemperature: '1140'
serialNumberConductivity: '832'
systemUploadTime: 1.0662179e+09
ship: Divcom3
scientist: ''
institute: ''
address: ''
cruise: Halifax Harbour
station: Stn 2
date: 1.0662179e+09
startTime: 1.0662323e+09
recoveryTime: .na
latitude: 44.6842667
longitude: -63.6438833
sampleInterval: 1.0
sampleIntervalUnits: s
filename: /Users/kelley/git/oce/create_data/ctd/ctd.cnv
```
